### ISSUE TITLE
Using directly with node (no ESM)

### ISSUE THREAD

**Issue by millette** [misund/get-best-contrast-color#12]
If your setup doesn't support ESM (import/export) yet, you'll have to include the dependency with

```js
const bestContrast = require('get-best-contrast-color').default
```

Note the necessary ```.default```.

Can it be fixed? If not, adding a line to the readme would be helpful.

**Comment by misund** [comment]
I'll be happy to review a PR adding a separate commonjs module.

I'll also happily accept readme PRs. :)

**Comment by millette** [comment]
I went with the simplest option :-)
